### PR TITLE
Update faraday and json

### PR DESCRIPTION
**Pull request by igas**

### CODE REVIEW

**Comment by DanielKehoe** [comment]
Please @marrony or others at Fauna, could we have a review and a merge of this PR? And release to RubyGems?

I'd like to use the faunadb-ruby driver and I'm blocked until faraday and json are updated here.

**Review by trevorsibanda — CHANGES_REQUESTED** [review]
Hi, sorry for the delayed response.  Did you try running tests after bumping up the gems? 
```bash
trevor@laptop:~/workspace/fauna/faunadb-ruby$ make test
bundle exec rake spec
/usr/bin/ruby2.5 -I/var/lib/gems/2.5.0/gems/rspec-core-3.9.2/lib:/var/lib/gems/2.5.0/gems/rspec-support-3.9.3/lib /var/lib/gems/2.5.0/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 59317
.................................................................................*......F...........................................................................................................................F...................F..

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Fauna::Query#expr round-trips special types
     # Support for auto-escaping of special types is deferred
     # ./spec/query_spec.rb:150
....
  3) Fauna Errors Fauna::UnexpectedError raised for parsing error
     Failure/Error: expect { stub_error(Faraday::ParsingError.new('parse error')).query('') }.to raise_error(Fauna::UnexpectedError, /parse error/)
     
       expected Fauna::UnexpectedError with message matching /parse error/, got #<Faraday::ParsingError #<Faraday::ParsingError: parse error>> with backtrace:
         # ./spec/errors_spec.rb:38:in `block in stub_error'
         # /var/lib/gems/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/test.rb:236:in `call'
         # ./lib/fauna/client.rb:236:in `call'
         # /var/lib/gems/2.5.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
         # /var/lib/gems/2.5.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
         # /var/lib/gems/2.5.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
         # ./lib/fauna/client.rb:217:in `perform_request'
         # ./lib/fauna/client.rb:179:in `execute'
         # ./lib/fauna/client.rb:116:in `query'
         # ./spec/errors_spec.rb:182:in `block (4 levels) in <top (required)>'
         # ./spec/errors_spec.rb:182:in `block (3 levels) in <top (required)>'
     # ./spec/errors_spec.rb:182:in `block (3 levels) in <top (required)>'

Finished in 6.23 seconds (files took 0.25157 seconds to load)
235 examples, 3 failures, 1 pending

Failed examples:

rspec ./spec/query_spec.rb:1067 # Fauna::Query#recursive references create nested keys
rspec ./spec/errors_spec.rb:54 # Fauna Errors parses invalid data
rspec ./spec/errors_spec.rb:181 # Fauna Errors Fauna::UnexpectedError raised for parsing error


```

**Comment by DanielKehoe** [comment]
I forked the gem and I've been using my own release in production. However, I've just been using it for a simple use case (writing to a database) so I haven't encountered any bugs. The test error may impact a query I'm not using.

**Comment by bradical** [comment]
@tomusiaka we're going to run into this too when we attempt to upgrade Ruby

**Pull request closed without merging**
